#!/usr/bin/env node

import { readFile, writeFile } from "node:fs/promises";
import * as path from "node:path";

import { format } from "prettier";

import { toolsetsForTool } from "../src/lib/toolsets.js";
import { getGitLabToolDefinitions } from "../src/tools/gitlab.js";

const outputPath = path.resolve(import.meta.dirname, "..", "docs", "tools-index.md");
const checkOnly = process.argv.includes("--check");
const generated = await format(renderToolIndex(), { parser: "markdown" });

if (checkOnly) {
  const existing = await readFile(outputPath, "utf8").catch(() => "");
  if (existing !== generated) {
    throw new Error("docs/tools-index.md is stale; run `pnpm docs:generate`");
  }
} else {
  await writeFile(outputPath, generated, "utf8");
}

function renderToolIndex(): string {
  const tools = getGitLabToolDefinitions()
    .map((tool) => ({
      name: tool.name,
      description: tool.description,
      capabilities: tool.capabilities.join(", "),
      scope: tool.scope.kind,
      toolsets: toolsetsForTool(tool.name).join(", ") || "—",
      availability: tool.compatibilityAlias ? "compatibility opt-in" : "default"
    }))
    .sort((left, right) => left.name.localeCompare(right.name));

  const lines = [
    "# Generated Tool Index",
    "",
    "<!-- This file is generated by scripts/generate-tool-index.ts. Do not edit manually. -->",
    "",
    `The registry contains **${tools.length} GitLab tools** plus \`health_check\`. Policy, toolset, feature, transport, and project-scope settings can hide tools at runtime.`,
    "",
    "| Tool | Capabilities | Scope | Toolsets | Availability | Description |",
    "| --- | --- | --- | --- | --- | --- |",
    ...tools.map(
      (tool) =>
        `| \`${tool.name}\` | ${escapeCell(tool.capabilities)} | ${escapeCell(tool.scope)} | ${escapeCell(tool.toolsets)} | ${escapeCell(tool.availability)} | ${escapeCell(tool.description)} |`
    ),
    ""
  ];

  return `${lines.join("\n")}\n`;
}

function escapeCell(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll(/\s+/g, " ").trim();
}
